---
title: "lab6"
author: "Claire"
date: "2019年4月8日"
output: html_document
---
###空間分析　Lab 6
####地理二　b06208028　甘佳昀
```{r results ='hide',message =FALSE,warning=FALSE}
library(rgdal)
library(aspace)
library(GISTools)
library(spdep)
library(dplyr)
library(ggplot2)
library(ggExtra)
library(RColorBrewer)#畫圖畫顏色的套件
library(classInt)
```
#1-1
```{r}
n<-c(0:100)
d<-dbinom(n, size = 500, prob = 0.002)
da<-data.frame(n,d)
ggplot(da,aes(x=n,y=d))+geom_col()+xlim(-0.5,6.5)
```

```{r}
mean1<-mean(rbinom(10000, size = 500, prob = 0.002))
sd1<-sd(rbinom(10000, size = 500, prob = 0.002))

paste("mean=",mean1,"；sd=",sd1)
```

#1-2
```{r}
nom<-dbinom(2, size = 500, prob = 0.002)
dp<-dpois(2,500*0.002)#前是想知道的機率對應的數量，後是期望值

paste("二項分布=",nom,"；poisson=",dp)
```

#2

#####畫出12*12，邊長為5000m的方格，並且計算方格內的學校個數以及它的平均值和變異數
```{r results ='hide',message =FALSE,warning=FALSE}
School <- readOGR(dsn = ".", layer = "Schools", encoding="utf8")
TW <- readOGR(dsn = ".", layer = "Popn_TWN2", encoding="utf8")


bb <- bbox(School)#bbox產生座標位置的極值
grd <- GridTopology(cellcentre.offset=c(bb[1,1]-200,bb[2,1]-200),
                    cellsize=c(5000,5000), cells.dim = c(12,12)) 

grd<-as.SpatialPolygons.GridTopology(grd,proj4string = TW@proj4string)
School@proj4string<-TW@proj4string
School.count<- poly.counts(School, grd) #數幾個

```

###step 1

#####H0:方格內的學校數的平均數=變異數

#####Ha:方格內的學校數的平均數<變異數

<br>

###step 2


#####計算統計量
```{r}
mean_c<-mean(School.count)
var_c<-var(School.count)
VMR<-var_c/mean_c
se<-sqrt(2/(144-1))
t<-(VMR-1)/se
```

### step 3

#####計算p-value
```{r}
p_value<-pt(t,df=144-1,lower.tail=F);paste("p-value:",p_value)

```

###step 4

#####設定α=0.05，得知α>p-value，足以否決HO

### step 5

#####拒絕「H0:方格內的學校數的平均數=變異數」這個假說，顯示方格內的學校數的平均數<變異數，屬於Clusterd(聚集)的分布狀況。